### ISSUE TITLE
Working from where!? Please, the suspense is killing me!

### ISSUE THREAD

**Issue by jakedt** [imjasonh/ImJasonH#1]
https://github.com/ImJasonH/ImJasonH/blob/d31cd62c1959d56734e457a9f0344bbeb440bb44/resume-crd.yaml#L189

**Comment by imjasonh** [comment]
Thank you for reporting this critical error, and for doing it promptly and responsibly. A lot of lives were saved today.

Fixed in https://github.com/ImJasonH/ImJasonH/commit/d05ef811f5166dd687c2cec97b0a7241e5cc02ad

**Comment by jakedt** [comment]
Thank you kind sir. Does your company offer a bug bounty rewards system?
